### ISSUE TITLE
Lambda Function

### ISSUE THREAD

**Issue by BandLinc** [awslabs/aws-cicd-workshop-cpt#4] opened 2021-03-09 04:07 UTC
Hi Team,

I am trying to create a Lambda function on the API Gateway but am getting an error that I do not have rights to do so. 

Is the issue on my end?  Please assist.

Thanks

**Comment by nyashamk** [comment] 2021-03-09 06:20
Hi @BandLinc ,

Thank you for reaching out. We would need more details to help isolate the cause of the issue. Would it be possible to share a screenshot of the full error ? Also I would suggest checking the IAM permissions of the user/role used to create the lambda function.

**Comment by BandLinc** [comment] 2021-03-09 06:42
Hello @nyashamk,
Granted permissions and now able to create. Thanks alot.

**Comment by BandLinc** [comment] 2021-03-09 06:59
![Screenshot from 2021-03-09 09-56-29](https://user-images.githubusercontent.com/17977638/110430901-19cdee80-80be-11eb-8679-5de55600e335.png)

**Comment by BandLinc** [comment] 2021-03-09 07:07
Now working well 
![image](https://user-images.githubusercontent.com/17977638/110431717-37e81e80-80bf-11eb-8979-426568c0de1f.png)

**Comment by nyashamk** [comment] 2021-03-09 11:40
Awesome, thank you for letting us know that it is now working well. :)

**Comment by nyashamk** [comment] 2021-03-10 07:33
Closing this issue as it is resolved. :)

**Closed as completed by nyashamk** 2021-03-10 07:33 UTC

**Comment by BandLinc** [comment] 2021-03-10 08:17
Thank you
